name: set-step-output

description: An action to pass the steps context data to the next job

inputs:
  steps:
    description: The stringified steps context data
    default: ''

outputs:
  step_data:
    description: The steps context data
    value: ${{ steps.set-step-output.outputs.step_data }}


runs:
  using: composite
  steps:
    - name: Set step output
      id: set-step-output
      run: echo "step_data=$(echo '${{ inputs.steps }}' | jq -c .)" >> $GITHUB_OUTPUT
      shell: bash
