name: example-config-updater

description: an example of using upload/download to pass the config object around

inputs:
  mode:
    description: the mode to run in
    required: true
    default: 'read'

  config:
    description: the config object to update
    required: false
    default: '{}'

  test:
    description: test input

outputs:
  config:
    description: the updated config object.

  artifactId:
    description: the updated config object as an artifact.

  test:
    description: test output

runs:
  using: node20
  main: dist/index.js
