name: example-config-updater

description: an example of using upload/download to pass the config object around

inputs:
  mode:
    description: 'the mode to run in: create, read, or write'
    required: true
    default: read

  artifactId:
    description: the artifact id to read the config object from.
    required: false

outputs:
  config:
    description: the updated config object.

  artifactId:
    description: the updated config object as an artifact.

runs:
  using: node20
  main: dist/index.js
