name: example-config-updater

description: an example of using upload/download to pass the config object around

outputs:
  config:
    description: the updated config object.

  artifactId:
    description: the updated config object as an artifact.

  test:
    description: test output

runs:
  using: node20
  main: dist/index.js
