name: example-config-updater

description: An example of using upload/download to pass the config object around. 

inputs:
  mode:
    description: 'the mode to run in: create, read, or write'
    required: true
    default: read

  artifactId:
    description: The artifact id to read the config object from.
    required: false

  config:
    description: The config object to update, in JSON string format.
    required: false

outputs:
  config:
    description: the updated config object, in JSON string format.

  artifactId:
    description: the updated config object as an artifact.

runs:
  using: node20
  main: dist/index.js
