name: action-env-test

# This workflow proves that env vars are available in called Actions without passing as inputs.
# And also proves they are NOT passed to called Workflows.

on: push

env:
  MY_ENV_VAR: Jabberwocky!

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: print job env var
        run: |
          echo "Using job environment variable:"
          echo "MY_ENV_VAR is $MY_ENV_VAR"        # MY_ENV_VAR is Jabberwocky!

      - name: Set up environment
        run: |
          echo "MY_ENV_VAR=Hello World" >> $GITHUB_ENV
      
      - name: Use environment variable
        run: |
          echo "Using previous step environment variable:"
          echo "MY_ENV_VAR is $MY_ENV_VAR"       # MY_ENV_VAR is Hello World

      - name: use step env var in action
        uses: ./actions/test-env-var
        env:
          MY_ENV_VAR: 'something else'           # in the Action, MY_ENV_VAR is something else

  new-env:
    runs-on: ubuntu-latest
    needs: set-env
    env:
      MY_ENV_VAR: Jabberwocky2               
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: print job env var
        run: |
          echo "Using job environment variable:"
          echo "MY_ENV_VAR is $MY_ENV_VAR"          # MY_ENV_VAR is Jabberwocky2
      
      - name: use job env var in action
        uses: ./actions/test-env-var                # in the Action, MY_ENV_VAR is Jabberwocky2

  call-new-wf:
    needs: new-env
    uses: ./.github/workflows/action-env-test-follower.yml
    # with:
    #   MY_ENV_VAR: Jabberwocky3