name: Checkout Tester

on: 
  workflow_dispatch:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: list
        run: ls -al

      - name: stash
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          include-hidden-files: true
