name: Clean Tester

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: clean workspace
        uses: ./actions/clean-workspace

      - name: look
        run: ls -la

      - name: create test file
        run: |
          echo 'starting ${{ github.job }}' >> testfile.txt
          ls -la

      - name: wipe workspace
        uses: ./actions/clean-workspace

      - name: check1
        run: ls -la
