name: Config ReaderWriter

on: push

# global env var
env:
  mascot: Mona

defaults:
  run:
    shell: bash

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: echo 'starting init'

      - name: create config
        uses: ./example-config-updater
        with:
          mode: create
        continue-on-error: true

      - name: done
        run: echo '::notice::${{ github.job }} done' >> $GITHUB_STEP_SUMMARY

  read:
    name: Read
    runs-on: ubuntu-latest
    needs: [init]

    steps:
      - name: read
        run: echo 'starting read'

      - name: read config
        uses: ./example-config-updater
        with:
          mode: read
        continue-on-error: true
      
      - name: done
        run: echo '::notice::${{ github.job }} done' >> $GITHUB_STEP_SUMMARY

  post:
    name: Post
    runs-on: ubuntu-latest
    needs: [read]

    steps:
      - name: post
        run: echo 'starting post'

      - name: done
        run: echo '::notice::${{ github.job }} done' >> $GITHUB_STEP_SUMMARY