name: Config ReaderWriter

on: push

# global env var
env:
  mascot: Mona

defaults:
  run:
    shell: bash

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: echo "init"