name: Config ReaderWriter

on: push

defaults:
  run:
    shell: bash

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: echo 'starting ${{ github.job }}'

      - name: checkout
        uses: actions/checkout@v4

      - name: stash action dir
        uses: actions/upload-artifact@v4
        with:
          name: actions
          path: actions

      - name: create config
        uses: ./actions/example-config-updater
        with:
          mode: create
        continue-on-error: true

      - name: done
        run: echo "::notice::${{ github.job }} done"

  read:
    name: Read
    runs-on: ubuntu-latest
    needs: [init]

    steps:
      - name: read
        run: echo 'starting ${{ github.job }}'
      
      - name: unstash action dir
        uses: actions/download-artifact@v4
        with:
          name: actions
          path: actions

      - name: read config
        uses: ./actions/example-config-updater
        with:
          mode: read
      
      - name: done
        run: echo "::notice::${{ github.job }} done"

  post:
    name: Post
    runs-on: ubuntu-latest
    needs: [read]

    steps:
      - name: post
        run: echo 'starting ${{ github.job }}'

      - name: done
        run: echo "::notice::${{ github.job }} done"
