name: input tester

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      run-type:
        description: "The type of run to kick off: build, deploy, both"
        required: true
        type: choice
        default: build only
        options:
          - build only
          - build and deploy
          - deploy only 

permissions:
  contents: read

jobs:
  input-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo input
        shell: bash
        run: |
          echo "event is ${{ github.event_name }}"
          echo "Input value is: ${{ inputs.run-type }}"
          echo "github context value is: ${{ toJSON(github) }}"
